name: ip sleep

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - run: curl ifconfig.me
    - run: |
        sudo apt update -y
        sudo apt install -y nginx
        sudo systemctl start nginx
    - run: sleep 180
