name: issues-test

on:
  issues:
    types: [labeled, edited]

permissions: {}

jobs:
  # use github-script to output the github context
  output:
    runs-on: ubuntu-slim
    steps:
    - name: output
      run: |
        echo ${{ toJSON(github) }}
    - uses: actions/github-script@v8
      with:
        script: |
          console.log(github.context)
