name: issue-labels

on:
  issues:
      types: [labeled]

permissions: {}

jobs:
  labeled:
    runs-on: ubuntu-slim
    if: contains(github.event.label.name, 'duplicate')
    #if: github.event.label.name == 'bug'
    steps:
    - uses: actions/github-script@v8
      with:
        script: |
          console.log(context)
          console.log(context.payload.issue.body)
  wf:
    uses: ./.github/workflows/issue-workflow-called.yml
