name: notify

on:
  workflow_dispatch:

permissions: {}

jobs:
  notify-success:
    runs-on: ubuntu-slim
    steps:
      - name: step1
        run: echo "success"
      - name: step2
        run: echo "success"
      - name: notify
        if: always()
        run: echo "notify result - ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
  notify-failure:
    runs-on: ubuntu-slim
    steps:
      - name: step1
        run: echo "failure" && exit 1
      - name: step2
        run: echo "failure"
      - name: notify
        if: always()
        run: echo "notify result - ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
