name: notify

on:
  workflow_dispatch:

jobs:
  notify-success:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "success"
      - name: step2
        run: echo "success"
      - name: notify
        if: always()
        run: echo ${{ job.status }} >> GITHUB_STEP_SUMMARY
  notify-failure:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "failure" && exit 1
      - name: step2
        run: echo "failure"
      - name: notify
        if: always()
        run: echo ${{ job.status }} >> GITHUB_STEP_SUMMARY
