name: Retry Workflow

on:
  workflow_run:
    workflows:
      # List of workflow names to watch for activity.
      # Explicitly listing workflows is required, wildcards are not supported.
      - failure-workflow
    types:
      - completed

jobs:
  retry:
    runs-on: ubuntu-latest
    # Only run if the workflow run failed and has not exhausted its attempts.
    if: github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt < 3
    steps:
      - name: Analyze jobs
        id: job-analysis
        uses: actions/github-script@v7
        with:
          script: |
            let response = [];

            const jobs = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });

            // Loop through all jobs and find the ones that failed.
            for (let job of jobs.data.jobs) {
              if (job.conclusion === 'failure') {
                let result = {
                  name: job.name,
                  job_id: job.id,
                  check_run_url: job.check_run_url,
                };

                response.push(result);
              }
            }

            return response;

      - name: Analyze Check Runs
        id: check-run-analysis
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            let response = "false";

            let jobs = ${{ steps.job-analysis.outputs.result }};

            for (let job of jobs) {
              let annotations = await github.rest.checks.listAnnotations({
                owner: context.repo.owner,
                repo: context.repo.repo,
                check_run_id: job.job_id
              });

              // If the job has an annotation with exit code 1, then we want to retry the workflow.
              let messages = await annotations.data.find(({ message }) => message.includes("with exit code 1"));

              if (messages) {
                response = "true";
                break; // Break out of the loop if we find a job that needs to be retried.
              }
            }

            return response;

      - name: Retry Workflow
        if: steps.check-run-analysis.outputs.result == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.actions.reRunWorkflow({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });

            return response;

      - name: Report rate-limit
        uses: collinmcneese/actions-rate-limit-reporter@main
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

  exhaust:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.run_attempt >= 3
    steps:
      - name: Exhausted
        run: |
          echo "Workflow exhausted after 3 attempts." >> $GITHUB_STEP_SUMMARY
