name: Retry Workflow

on:
  workflow_run:
    workflows:
      - failure-workflow
    types:
      - completed

jobs:
  retry:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Analyze jobs
        id: job-analysis
        uses: actions/github-script@v7
        with:
          script: |
            let response = [];
            const jobs = await github.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id
            });
            for (let job of jobs.data.jobs) {
              if (job.conclusion === 'failure') {
                let result = {
                  name: job.name,
                  run_id: job.run_id,
                  check_run_url: job.check_run_url,
                };
                response.push(result);
              }
            }
            return response;
      - name: Retry jobs
        run: echo "${{ steps.job-analysis.outputs.result }}" | jq
